project:
  type: website

website:
  title: "Blue PulseðŸ’§"
  navbar:


    right: 
      - href: index.qmd
        text: Overview
      - href: "Proposal.html"
        text: "Proposal"
    
    
    
        
      - text: "Prototype"
        menu:
        - text: "WASH-Based Health Trend Analysis"
          href: "Prototype/Forcasting.html"



      - text: "Team"
        menu:
        - text: "About this project"
          href: about.qmd
        - text: "Meeting Minutes"
          href: "MeetingMinutes.html"
      



format:
  html:
    css: styles.css  # Reference external CSS file
    theme: darkly
    toc: true

editor: visual


